path: C:/Users/Simple/Desktop/Smart-parking-IoT/AI_Frontend/license_plate # dataset root dir
train: train # train images \
val: valid # val images \
test: # test images (optional)

# Classes
names:
  0: Bien_so_xe